#!/bin/bash

WHITELIST_DIRS="apps/ packages/ services/"

# Get list of changed files
CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E "(${WHITELIST_DIRS})" || true)

# Only proceed if there are changes in apps/ or packages/
if [ -n "$CHANGED_FILES" ]; then
    echo "Running pre-commit hooks for changes in apps/ and packages/..."

    echo "Formatting..."
    pnpm format

    git add .
else
    echo "No changes in white listed directories, skipping pre-commit hooks."
fi